/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HoneyBulmaStyle {
    }
}
declare global {
    interface HTMLHoneyBulmaStyleElement extends Components.HoneyBulmaStyle, HTMLStencilElement {
    }
    var HTMLHoneyBulmaStyleElement: {
        prototype: HTMLHoneyBulmaStyleElement;
        new (): HTMLHoneyBulmaStyleElement;
    };
    interface HTMLElementTagNameMap {
        "honey-bulma-style": HTMLHoneyBulmaStyleElement;
    }
}
declare namespace LocalJSX {
    interface HoneyBulmaStyle {
    }
    interface IntrinsicElements {
        "honey-bulma-style": HoneyBulmaStyle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "honey-bulma-style": LocalJSX.HoneyBulmaStyle & JSXBase.HTMLAttributes<HTMLHoneyBulmaStyleElement>;
        }
    }
}
